name: "🕷️ Bug Report - Specific Linter"
description: Report errors or unexpected behavior
type: Bug
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: Please make sure to [search for existing issues](https://github.com/oxsecurity/megalinter/issues) before filing a new one!

  - type: dropdown
    attributes:
      label: MegaLinter version
      description: Older versions are not be supported.
      options:
        - Latest
        - Beta
      default: 0
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Usage method
      description: How / Where are you using MegaLinter?
      multiple: true
      options:
        - Azure Pipelines
        - Bitbucket Pipelines
        - Concourse
        - Docker container
        - Drone CI
        - GitHub Action
        - GitLab CI
        - Jenkins
        - Run MegaLinter locally
        - Other (please specify in "Steps to Reproduce")
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Linter
      description: Select the linter that you having trouble with.
      options:
        - actionlint
        - ansible-lint
        - bandit
        - black
        - cfn-lint
        - checkmake
        - checkov
        - checkstyle
        - clang-format
        - clj-kondo
        - cljstyle
        - coffeelint
        - dartanalyzer
        - detekt
        - djlint
        - dotenv-linter
        - editorconfig-checker
        - flake8
        - gherkin-lint
        - git_diff
        - golangci-lint
        - graphql-schema-linter
        - grype
        - hadolint
        - helm
        - htmlhint
        - isort
        - jsonlint
        - kics
        - ktlint
        - kubeconform
        - kubescape
        - lightning-flow-scanner
        - ls-lint
        - luacheck
        - markdown-link-check
        - markdown-table-formatter
        - markdownlint
        - mypy
        - npm-groovy-lint
        - npm-package-json-lint
        - perlcritic
        - php-cs-fixer
        - phpcs
        - phplint
        - phpstan
        - prettier
        - psalm
        - pylint
        - remark-lint
        - revive
        - rst-lint
        - rstcheck
        - rstfmt
        - rubocop
        - ruff
        - scalafix
        - selene
        - sfdx-scanner-apex
        - sfdx-scanner-aura
        - sfdx-scanner-lwc
        - shfmt
        - snakefmt
        - snakemake
        - spectral
        - sqlfluff
        - stylelint
        - stylua
        - swiftlint
        - tekton-lint
        - terraform-fmt
        - terragrunt
        - terrascan
        - trivy
        - trivy-sbom
        - trufflehog
        - v8r
        - yamllint
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: We highly suggest including screenshots, output logs, and code snippets.
      placeholder: Having detailed steps helps us reproduce the bug.
    validations:
      required: true

  - type: textarea
    attributes:
      label: ✔️ Expected Behavior
      placeholder: What were you expecting?
    validations:
      required: false

  - type: textarea
    attributes:
      label: ❌ Actual Behavior
      placeholder: What happened instead?
    validations:
      required: false
