---
#########################
#########################
## Deploy Docker Image ##
#########################
#########################

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#######################################
# Start the job on all push to main #
#######################################
#############################
# Start the job on all push #
#############################
name: "Build & Deploy - DEV - TOMS"
on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - .github/CONTRIBUTING.md
      - CHANGELOG.md
      - README.md
      - .github/workflows/slash-command-dispatch.yml
      - .github/workflows/help-command.yml
      - .github/workflows/build-command.yml
  pull_request:
    branches-ignore: []
    paths-ignore:
      - .github/CONTRIBUTING.md
      - CHANGELOG.md
      - README.md
      - .github/workflows/slash-command-dispatch.yml
      - .github/workflows/help-command.yml
      - .github/workflows/build-command.yml

###############
# Set the Job #
###############
concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  build:
    # Name the Job
    name: Deploy Docker Image - DEV - TOMS
    # Set the agent to run on
    runs-on: ubuntu-latest
    permissions: read-all
    # Prevent duplicate run from happening when a forked push is committed
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository) && !contains(github.event.head_commit.message, 'skip deploy')
    # Set max build time for the job
    timeout-minutes: 120
    ##################
    # Load all steps #
    ##################
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Free disk space
      - name: Free Disk space
        shell: bash
        run: |
          sudo rm -rf /usr/local/lib/android  # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
          sudo rm -rf /opt/ghc
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Docker Metadata action
        uses: docker/metadata-action@v5.5.1
        id: meta
        with:
          images: |
            ${{ github.repository }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # TEMP Authenticates with Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      ###################################
      # Build image locally for testing #
      ###################################
      - name: Build MegaLinter Docker Image (quick)
        id: docker_build_quick
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile-quick
          platforms: linux/amd64
          build-args: |
            BUILD_DATE=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            BUILD_VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
            BUILD_REVISION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
            MEGA_LINTER_BASE_IMAGE="oxsecurity/megalinter:beta"
          load: true
          push: false
          secrets: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          tags: ${{ steps.meta.outputs.tags }}
        timeout-minutes: 90

      #######################################
      # Build image (full for forked repos) #
      #######################################
      - name: Build MegaLinter Docker Image (full from forks)
        if: |
          (
          (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository) ||
          (github.event_name == 'push' && github.repository != 'oxsecurity/megalinter')
          )
          &&
          !contains(github.event.head_commit.message, 'quick build')
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          build-args: |
            BUILD_DATE=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            BUILD_VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
            BUILD_REVISION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
          load: true
          push: false
          secrets: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          tags: ${{ steps.meta.outputs.tags }}
        timeout-minutes: 90

      ####################################
      # Build image (full for main repo) #
      ####################################
      - name: Build MegaLinter Docker Image (full from main repo) & push
        if: |
          (
          (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) ||
          (github.event_name == 'push' && github.repository == 'oxsecurity/megalinter')
          )
          &&
          !contains(github.event.head_commit.message, 'quick build')
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          build-args: |
            BUILD_DATE=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            BUILD_VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
            BUILD_REVISION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
          load: true
          push: false
          secrets: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          tags: ${{ steps.meta.outputs.tags }}

      # Clean docker build cache
      - name: Clean docker buildx cache
        run: docker buildx prune --force

      # Upload MegaLinter artifacts
      - name: Archive production artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
            mega-linter.log
            linter-helps.json
            linter-versions.json

      - name: debug
        if: success() || failure()
        run: echo ${{ steps.docker_build.outcome }}

      # Clean disk space
      - name: Clear disk space
        run: |
          sudo rm -rf /opt/ghc
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo swapoff -a || true
          sudo rm -f /swapfile || true
          sudo apt clean || true
